apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-production
  annotations:
    argo.octopus.com/project: "argo"
    argo.octopus.com/environment: "production"
    argo.octopus.com/image-replace-paths: "docker.io/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path:  manifests/helloworld-production/
    repoURL: https://github.com/FinnianDempsey/gitops-apps.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - 'values.yaml'
  destination:
    name: in-cluster
    namespace: production
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
