apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: nginx-helloworld/app/
    repoURL: https://github.com/FinnianDempsey/gitops-apps.git
    targetRevision: HEAD
    helm:
          valueFiles:
          - 'values.yaml'
  destination:
    name: in-cluster
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false