apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld
spec:
  generators:
    - list:
        elements:
          - namespace: staging
          - namespace: production
  template:
    metadata:
      name: helloworld-{{.namespace}}
    spec:
      project: default
      source:
        path: helloworld/app/
        repoURL: https://github.com/FinnianDempsey/gitops-apps.git
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: {{.namespace}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=false