apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld
spec:
  generators:
  - list:
      elements:
        - environment: staging
        - environment: production
  template:
    metadata:
      name: 'helloworld-{{environment}}'
    spec:
      project: default
      source:
        path: nginx-helloworld/app/
        repoURL: https://github.com/FinnianDempsey/gitops-apps.git
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: '{{environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=false